sudo: false
language: node_js
node_js:
- node
script:
- npm install
- npm test
after_success:
- npm run build
- cd dist && zip -x .DS_Store -r flex.zip . && cd ..
- NAME=$TRAVIS_BRANCH
- "[[ $TRAVIS_PULL_REQUEST != 'false' ]] && NAME=$TRAVIS_PULL_REQUEST"
- "[[ -n $TRAVIS_TAG ]] && NAME=$TRAVIS_TAG"
- curl -i -X POST -F "branch=$TRAVIS_BRANCH" -F "commit=$TRAVIS_COMMIT" -F "key=$OCBLOBS_KEY"
  -F 'upfile=@dist/flex.zip' https://flex.blobs.oopscommand.com/upload.php
env:
  global:
    secure: MsaqYn/eAFaaREC7vh90F1S6of94uZ8ZG1F00GA59FJDK68Va3vunOHCY2Czh/z1UxiAgsyTpwzFxHvPU5MzVRt/EBv8itgq8IP2/33U+rO9Q/zlnOPFWB7/hrljG6M5sjyKCXfddA3xntYi7Pnp9pDaL3x2EIG9J9LlweHFOOGVD2V2gr4WMm0gxC1R+Fc71cxGUTBIT84d16M+0b2/ldLfVKi7wMhIoZLQ/gHQfvTZXUe6SmY3YkJreZ9FyUZ5Z8mk8D8XibDfGG9oIA1eJOldQUWiYiCfvs+P6TeM3h8xio7z6SNSKmN/ZPnIZNTvs1gWoUGQ2RF9zpXcj12hqgb+bOYKjR7kgQ7HbYTc5/N+4gNP+pAE5ac6f5W7CacBA5jxQ9A9RnZFEz88JgtUYKSTt5rXVLY78EKtP8OGt6bxsgHrW0XyS7bALYV8pdUGi37t+yjWOE9+UqxVpkzfSYItaNYvXSJ9svlm68vQv2ENFILBYHyEAv8zlkpBKx4oCI08TsAi1oHJGSWPU+GsSVC8OrRt1iRKDX96Uf6ZNf4/zJtaQh7UWX8N4s+hqODEDDk27cs8LsMMqW5yWuNn7o4MSIIuCNDSG8EHS825lUGvTsT7F1GasrE1r6Iy1KzcFF6fhCuDkQ7bhrlhb9UvnJPQ97CdQjiHTOLoZJXQcPw=
